### ISSUE TITLE
Android debug build crashes after upgrade from 2.0.0 to 3.0.0

### ISSUE THREAD

**Issue by ferdicus** [oblador/react-native-keychain#158]
The app crashes upon being copied over to the device, here my settings:

react-native: 0.57.4
react-native-keychain: 3.0.0
Android Studio: 3.2.1 
Gradle: 4.6 
node: 8.12.0

I'm aware, that I'm on the bleeding edge right now, interestingly though everything runs fine with version `2.0.0` of react-native-keychain.

**Comment by vonovak** [comment]
@ferdicus please add a repro or at least a stacktrace, otherwise this is impossible to fix

**Comment by ferdicus** [comment]
you're right, I'll add the stacktrace from adb logcat:

```
11-21 16:10:06.706 25907 25907 E AndroidRuntime: java.lang.RuntimeException: Unable to instantiate application <MYAPP>.MainApplication: java.lang.ClassNotFoundException: Didn't find class "<MYAPP>.MainApplication" on path: DexPathList[[zip file "/data/app/<MYAPP>-1/base.apk"],nativeLibraryDirectories=[/data/app/<MYAPP>-1/lib/arm, /data/app/<MYAPP>-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
11-21 16:10:06.706 25907 25907 E AndroidRuntime: 	at android.app.LoadedApk.makeApplication(LoadedApk.java:846)
11-21 16:10:06.706 25907 25907 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5948)
11-21 16:10:06.706 25907 25907 E AndroidRuntime: 	at android.app.ActivityThread.-wrap3(ActivityThread.java)
11-21 16:10:06.706 25907 25907 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1707)
11-21 16:10:06.706 25907 25907 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
11-21 16:10:06.706 25907 25907 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
11-21 16:10:06.706 25907 25907 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6780)
11-21 16:10:06.706 25907 25907 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-21 16:10:06.706 25907 25907 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1500)
11-21 16:10:06.706 25907 25907 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1390)
11-21 16:10:06.706 25907 25907 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "<MYAPP>.MainApplication" on path: DexPathList[[zip file "/data/app/<MYAPP>-1/base.apk"],nativeLibraryDirectories=[/data/app/<MYAPP>-1/lib/arm, /data/app/<MYAPP>n-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
11-21 16:10:06.706 25907 25907 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
11-21 16:10:06.706 25907 25907 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
11-21 16:10:06.706 25907 25907 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
11-21 16:10:06.706 25907 25907 E AndroidRuntime: 	at android.app.Instrumentation.newApplication(Instrumentation.java:1000)
11-21 16:10:06.706 25907 25907 E AndroidRuntime: 	at android.app.LoadedApk.makeApplication(LoadedApk.java:835)
11-21 16:10:06.706 25907 25907 E AndroidRuntime: 	... 9 more
```

**Comment by vonovak** [comment]
closing as outdated, please open a new issue if the problem persists, and please include a repro.
