### ISSUE TITLE
Unitesting error

### ISSUE THREAD

**Issue by eladgel** [oblador/react-native-keychain#16]
I get the next error when running a npm test with Jest on the code:

` 
SyntaxError: /Users/gelo/Documents/react/honeybook-mobile/node_modules/react-native-keychain/index.ios.js: Unexpected token (16:10)
  14 |    */
  15 |   setInternetCredentials: function(
>   16 |     server: string,
     |           ^
  17 |     username: string,
  18 |     password: string,
  19 |     callback?: ?(error: ?Error) => void
    at Parser.pp.raise (/Users/gelo/Documents/react/honeybook-mobile/node_modules/babylon/index.js:1425:13)
    at Parser.pp.unexpected (/Users/gelo/Documents/react/honeybook-mobile/node_modules/babylon/index.js:2907:8)
    at Parser.pp.expect (/Users/gelo/Documents/react/honeybook-mobile/node_modules/babylon/index.js:2901:33)
    at Parser.pp.parseBindingList (/Users/gelo/Documents/react/honeybook-mobile/node_modules/babylon/index.js:1605:12)
    at Parser.pp.parseFunctionParams (/Users/gelo/Documents/react/honeybook-mobile/node_modules/babylon/index.js:2415:22)
    at Parser.pp.parseFunction (/Users/gelo/Documents/react/honeybook-mobile/node_modules/babylon/index.js:2405:8)
    at Parser.pp.parseFunctionExpression (/Users/gelo/Documents/react/honeybook-mobile/node_modules/babylon/index.js:764:17)
    at Parser.pp.parseExprAtom (/Users/gelo/Documents/react/honeybook-mobile/node_modules/babylon/index.js:726:19)
    at Parser.pp.parseExprSubscripts (/Users/gelo/Documents/react/honeybook-mobile/node_modules/babylon/index.js:509:19)
    at Parser.pp.parseMaybeUnary (/Users/gelo/Documents/react/honeybook-mobile/node_modules/babylon/index.js:489:19) `

**Comment by oblador** [comment]
It's because this module is using flow. Try using https://github.com/babel/babel-jest
