### ISSUE TITLE
how to mock setInternetCredentials and getInternetCredentials

### ISSUE THREAD

**Issue by loic-lopez** [oblador/react-native-keychain#160]
Hello,
I did : 
```node
jest.mock("react-native-keychain", () => {
  return {
    setInternetCredentials: jest.fn(
      (server, username, password) => new Promise((resolve, reject) => resolve(true))
    ),
    getInternetCredentials: jest.fn((server) => new Promise((resolve, reject) => resolve(true))),
  };
});
```

And i got this error: 
```
 TypeError: Cannot read property 'setInternetCredentialsForServer' of undefined

       9 |  */
      10 | export async function save(tokens: TokenResponse, server: string) {
    > 11 |   await ReactNativeKeychain.setInternetCredentials(server, null, JSON.stringify(tokens));
         |                             ^
      12 |   return true;
      13 | }
      14 | 

      at Object.setInternetCredentials (node_modules/react-native-keychain/index.js:103:28)
      at Object.save (src/lib/keychain.ts:11:29)
      at Object.<anonymous>.test (test/keychain.test.ts:17:10)
```

It is possible to mock it?
Thanks for reply. :)

**Comment by loic-lopez** [comment]
Hi, 

i've created a wrapper:
```
import * as ReactNativeKeychain from "react-native-keychain";
import { ITokenResponse } from "src/services/api";

/**
 * Saves some credentials securely.
 *
 * @param tokens
 * @param server The server these creds are for.
 */
export async function save(tokens: ITokenResponse, server: string): Promise<boolean> {
  await ReactNativeKeychain.setInternetCredentials(server, 'ExoRun', JSON.stringify(tokens));
  return true;
}
```

And there is my test: 
```
import { load, save } from "src/lib/keychain";
import * as ReactNativeKeychain from "react-native-keychain";

const credentials = {
  token_type: "bearer",
  expires_in: 200,
  access_token: "iejaziojeoizajeza",
  refresh_token: "lapoazkeokapekza"
};

jest.mock("react-native-keychain", () => {
  return {
    setInternetCredentials: jest.fn(
      (server, username, password) => new Promise((resolve, reject) => resolve(true))
    ),
    getInternetCredentials: jest.fn((server) => new Promise((resolve, reject) => resolve(true))),
  };
});

const server = 'test';


test("save", async () => {
  await save(credentials, server);
  console.log("ok");
  // return
});
```

But the same error appear.
Can you help me please?
