### ISSUE TITLE
Android debug build failing

### ISSUE THREAD

**Issue by sadikyalcin** [oblador/react-native-keychain#433]
First time I'm doing anything to do with keychain so forgive my ignorance on the matter. Debug build is failing on Android (`yarn android deviceId={id})`. Logs from the terminal below. Any help/guidance is appreciated.

```
RN: 0.63.3
react-native-keychain: ^6.2.0
buildToolsVersion: 29.0.2
minSdkVersion: 21
compileSdkVersion: 29
targetSdkVersion: 29
```

```
Task :react-native-keychain:testDebugUnitTest

com.oblador.keychain.KeychainModuleTests

  Test testGetSecurityLevel_NoBiometry_api28 FAILED (6.9s)

  org.mockito.exceptions.base.MockitoAssertionError: There were multiple verification failures:
  1. Argument(s) are different! Wanted:
  promise.resolve("SECURE_HARDWARE");
  -> at com.oblador.keychain.KeychainModuleTests.testGetSecurityLevel_NoBiometry_api28(KeychainModuleTests.java:407)
  Actual invocations have different arguments:
  promise.resolve("SECURE_SOFTWARE");
  -> at com.oblador.keychain.KeychainModule.getSecurityLevel(KeychainModule.java:434)


  Test testExtractAesCbc_NoFingerprintConfigured_api23 FAILED (3.7s)

  java.lang.AssertionError: 
  Expected: is <true>
       but: was <false>
      at com.oblador.keychain.KeychainModuleTests.testExtractAesCbc_NoFingerprintConfigured_api23(KeychainModuleTests.java:233)

  Test testGetSecurityLevel_NoBiometry_NoSecuredHardware_api28 PASSED
  Test testExtractRsaEcb_EnabledFingerprint_api23 FAILED

  java.lang.AssertionError: 
  Expected: is <true>
       but: was <false>
      at com.oblador.keychain.KeychainModuleTests.testExtractRsaEcb_EnabledFingerprint_api23(KeychainModuleTests.java:255)

  Test testExtractRsaEcb_EnabledFingerprint_api28 PASSED
  Test testGetSecurityLevel_Unspecified_api19 FAILED (1.3s)

  java.lang.RuntimeException: java.lang.RuntimeException: Failed to parse package /Users/admin/Sites/engie/node_modules/react-native-keychain/android/build/intermediates/apk_for_local_test/debugUnitTest/packageDebugUnitTestForUnitTest/apk-for-local-test.ap_: /Users/admin/Sites/engie/node_modules/react-native-keychain/android/build/intermediates/apk_for_local_test/debugUnitTest/packageDebugUnitTestForUnitTest/apk-for-local-test.ap_ (at Binary XML file line #5): Requires newer sdk version #21 (current version is #19)

  Caused by: java.lang.RuntimeException: Failed to parse package /Users/admin/Sites/engie/node_modules/react-native-keychain/android/build/intermediates/apk_for_local_test/debugUnitTest/packageDebugUnitTestForUnitTest/apk-for-local-test.ap_: /Users/admin/Sites/engie/node_modules/react-native-keychain/android/build/intermediates/apk_for_local_test/debugUnitTest/packageDebugUnitTestForUnitTest/apk-for-local-test.ap_ (at Binary XML file line #5): Requires newer sdk version #21 (current version is #19)


  Test testGetSecurityLevel_Unspecified_api21 PASSED (2.3s)
  Test testGetSecurityLevel_Unspecified_api23 FAILED

  org.mockito.exceptions.base.MockitoAssertionError: There were multiple verification failures:
  1. Argument(s) are different! Wanted:
  promise.resolve("SECURE_HARDWARE");
  -> at com.oblador.keychain.KeychainModuleTests.testGetSecurityLevel_Unspecified_api23(KeychainModuleTests.java:359)
  Actual invocations have different arguments:
  promise.resolve("SECURE_SOFTWARE");
  -> at com.oblador.keychain.KeychainModule.getSecurityLevel(KeychainModule.java:434)


  Test testGetSecurityLevel_Unspecified_api28 FAILED

  org.mockito.exceptions.base.MockitoAssertionError: There were multiple verification failures:
  1. Argument(s) are different! Wanted:
  promise.resolve("SECURE_HARDWARE");
  -> at com.oblador.keychain.KeychainModuleTests.testGetSecurityLevel_Unspecified_api28(KeychainModuleTests.java:344)
  Actual invocations have different arguments:
  promise.resolve("SECURE_SOFTWARE");
  -> at com.oblador.keychain.KeychainModule.getSecurityLevel(KeychainModule.java:434)


  Test testDowngradeBiometricToAes_api28 FAILED

  org.mockito.exceptions.base.MockitoException: 
  No argument value was captured!
  You might have forgotten to use argument.capture() in verify()...
  ...or you used capture() in stubbing but stubbed method was not called.
  Be aware that it is recommended to use capture() only with verify()
  
  Examples of correct argument capturing:
      ArgumentCaptor<Person> argument = ArgumentCaptor.forClass(Person.class);
      verify(mock).doSomething(argument.capture());
      assertEquals("John", argument.getValue().getName());
      at com.oblador.keychain.KeychainModuleTests.testDowngradeBiometricToAes_api28(KeychainModuleTests.java:464)

  Test testFingerprintNoHardware_api21 PASSED
  Test testExtractFacebookConceal_NoHardware_api19 FAILED

  java.lang.RuntimeException: java.lang.RuntimeException: Failed to parse package /Users/admin/Sites/engie/node_modules/react-native-keychain/android/build/intermediates/apk_for_local_test/debugUnitTest/packageDebugUnitTestForUnitTest/apk-for-local-test.ap_: /Users/admin/Sites/engie/node_modules/react-native-keychain/android/build/intermediates/apk_for_local_test/debugUnitTest/packageDebugUnitTestForUnitTest/apk-for-local-test.ap_ (at Binary XML file line #5): Requires newer sdk version #21 (current version is #19)

  Caused by: java.lang.RuntimeException: Failed to parse package /Users/admin/Sites/engie/node_modules/react-native-keychain/android/build/intermediates/apk_for_local_test/debugUnitTest/packageDebugUnitTestForUnitTest/apk-for-local-test.ap_: /Users/admin/Sites/engie/node_modules/react-native-keychain/android/build/intermediates/apk_for_local_test/debugUnitTest/packageDebugUnitTestForUnitTest/apk-for-local-test.ap_ (at Binary XML file line #5): Requires newer sdk version #21 (current version is #19)


  Test testFingerprintAvailableButNotConfigured_api23 PASSED
  Test testMigrateStorageFromOlder_api23 PASSED
  Test testFingerprintConfigured_api23 FAILED

  java.lang.AssertionError: 
  Expected: is <true>
       but: was <false>
      at com.oblador.keychain.KeychainModuleTests.testFingerprintConfigured_api23(KeychainModuleTests.java:166)

  Test testFingerprintConfigured_api28 PASSED

com.oblador.keychain.cipherStorage.CipherStorageKeystoreRsaEcbTests

  Test testVerifySecureHardwareAvailability_api28 FAILED

  java.lang.AssertionError: 
  Expected: is <true>
       but: was <false>
      at com.oblador.keychain.cipherStorage.CipherStorageKeystoreRsaEcbTests.testVerifySecureHardwareAvailability_api28(CipherStorageKeystoreRsaEcbTests.java:99)

  Test testGetSecurityLevel_api23 FAILED

  java.security.NoSuchProviderException: JCE cannot authenticate the provider AndroidKeyStore
      at com.oblador.keychain.cipherStorage.CipherStorageKeystoreRsaEcbTests.testGetSecurityLevel_api23(CipherStorageKeystoreRsaEcbTests.java:75)
  Caused by: java.util.jar.JarException: Class is on the bootclasspath
      at com.oblador.keychain.cipherStorage.CipherStorageKeystoreRsaEcbTests.testGetSecurityLevel_api23(CipherStorageKeystoreRsaEcbTests.java:75)


com.oblador.keychain.cipherStorage.CipherStorageKeystoreAesCbcTests

  Test testGetSecurityLevel_api23 PASSED

FAILURE: Executed 19 tests in 16.2s (11 failed)


19 tests completed, 11 failed

> Task :react-native-keychain:testDebugUnitTest FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-keychain:testDebugUnitTest'.
> There were failing tests. See the report at: file:///Users/admin/Sites/engie/node_modules/react-native-keychain/android/build/reports/tests/testDebugUnitTest/index.html
```

**Comment by thomasrehm** [comment]
having the same problem. any idea on how to fix it, @oblador ?

**Comment by sgal** [comment]
@thomasrehm @sadikyalcin It should be fixed by this commit https://github.com/oblador/react-native-keychain/commit/2ded4a7d900d87a7b7416a3b4543d3eee6a90faa. Please get the latest master and try again.

**Comment by DorianMazur** [comment]
This issue is fixed
