### ISSUE TITLE
Unit tests failed

### ISSUE THREAD

**Issue by ivorysunder** [oblador/react-native-keychain#452]
I tried to use this lib for touch/faceid auth but stumbled into a problem with build
it fails one last test suit and won't build at all. 
Trying to build for pixel 3a emulator 
SDK ver 29
Android version 11

Tried to run it on One Plus 8 Pro T ( Oxygen OS 11.0.4.4.IN11AA ) same results
Main question is: 

**Will it be fixed any time soon? I need to implement this feature right now and i don't want to use less popular/less supported libs. Would be nice to know that you working on it and some estimations when it will work. If possible respond in comment to make me and other people know about current status. Thx in advance.**

```
Task :react-native-keychain:testDebugUnitTest

com.oblador.keychain.cipherStorage.CipherStorageKeystoreAesCbcTests

  Test testGetSecurityLevel_api23 PASSED (4.4s)

com.oblador.keychain.cipherStorage.CipherStorageKeystoreRsaEcbTests

  Test testVerifySecureHardwareAvailability_api28 PASSED (4.4s)
  Test testGetSecurityLevel_api23 PASSED

com.oblador.keychain.KeychainModuleTests

  Test testGetSecurityLevel_NoBiometry_api28 PASSED
  Test testExtractAesCbc_NoFingerprintConfigured_api23 PASSED
  Test testGetSecurityLevel_NoBiometry_NoSecuredHardware_api28 PASSED
  Test testExtractRsaEcb_EnabledFingerprint_api23 FAILED

  java.lang.AssertionError: 
  Expected: is <true>
       but: was <false>
      at com.oblador.keychain.KeychainModuleTests.testExtractRsaEcb_EnabledFingerprint_api23(KeychainModuleTests.java:255)

  Test testExtractRsaEcb_EnabledFingerprint_api28 PASSED
  Test testGetSecurityLevel_Unspecified_api19 PASSED (1.7s)
  Test testGetSecurityLevel_Unspecified_api21 PASSED (1.8s)
  Test testGetSecurityLevel_Unspecified_api23 PASSED
  Test testGetSecurityLevel_Unspecified_api28 PASSED
  Test testDowngradeBiometricToAes_api28 FAILED

  org.mockito.exceptions.base.MockitoException: 
  No argument value was captured!
  You might have forgotten to use argument.capture() in verify()...
  ...or you used capture() in stubbing but stubbed method was not called.
  Be aware that it is recommended to use capture() only with verify()

  Examples of correct argument capturing:
      ArgumentCaptor<Person> argument = ArgumentCaptor.forClass(Person.class);
      verify(mock).doSomething(argument.capture());
      assertEquals("John", argument.getValue().getName());
      at com.oblador.keychain.KeychainModuleTests.testDowngradeBiometricToAes_api28(KeychainModuleTests.java:464)

  Test testFingerprintNoHardware_api21 PASSED
  Test testExtractFacebookConceal_NoHardware_api19 PASSED
  Test testFingerprintAvailableButNotConfigured_api23 PASSED
  Test testMigrateStorageFromOlder_api23 PASSED
  Test testFingerprintConfigured_api23 FAILED

  java.lang.AssertionError: 
  Expected: is <true>
       but: was <false>
      at com.oblador.keychain.KeychainModuleTests.testFingerprintConfigured_api23(KeychainModuleTests.java:166)

  Test testFingerprintConfigured_api28 PASSED

FAILURE: Executed 19 tests in 14.4s (3 failed)


19 tests completed, 3 failed

> Task :react-native-keychain:testDebugUnitTest FAILED
```

**Comment by oblador** [comment]
Hi, I believe this is fixed by this commit https://github.com/oblador/react-native-keychain/commit/2ded4a7d900d87a7b7416a3b4543d3eee6a90faa

**Comment by ivorysunder** [comment]
Thx for response & fix! When it'll be published? @oblador
