### ISSUE TITLE
AndroidX-1.6.0 causing crash with "Method addObserver must be called on the main thread"

### ISSUE THREAD

**Issue by Kikketer** [oblador/react-native-keychain#503]
I've had to specifically set the AndroidX to a specific version due to issues related to other libraries:

app/build.gradle
```
...
implementation "androidx.core:core-ktx:1.6.0"
...
```

After adding this library to the dependencies (and not even using it yet) I get this error:
```
E/unknown:ReactNative: CatalystInstanceImpl caught native exception
    java.lang.IllegalStateException: Method addObserver must be called on the main thread
        at androidx.lifecycle.LifecycleRegistry.enforceMainThreadIfNeeded(LifecycleRegistry.java:317)
        at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.java:172)
        ...
```

This is the Android build.

If I remove the use of this library, the error goes away (but obviously isn't really a solve).

**Comment by oblador** [comment]
Hi, 
It would be useful to get the full stack trace here as I cannot find any references to `addObserver` nor `core-ktx` in the source code.
