### ISSUE TITLE
Task :react-native-keychain:extractReleaseAnnotations FAILED

### ISSUE THREAD

**Issue by Mitesh-2009** [oblador/react-native-keychain#520]
![Screenshot 2021-12-11 at 5 49 51 PM](https://user-images.githubusercontent.com/34374930/145676338-2a683bb0-0ca8-46cf-ad90-730e08ffde79.png)

"react": "17.0.2",
"react-native": "0.66.3",
"react-native-keychain": "^8.0.0"

Error occurs during creating release build, Please help me to solve this error

**Comment by nagarajbalan** [comment]
I am also facing same issue

**Comment by gabpaet** [comment]
+1 on this issue

**Comment by bahmandamia6982** [comment]
Same issue occurred for me while making `release` on some nodejs modules not just `react-native-keychain`

**Comment by HarishJangra** [comment]
still facing this issue when using compileSdkVersion 31. Does anyone have any solution?

**Comment by mwmcode** [comment]
has anyone found a solution for this?

**Comment by MiteshJabuani** [comment]
using     "react-native-keychain": "^8.0.0",
"react": "17.0.2",
"react-native": "0.68.0"


working fine.

**Comment by ashishAmz** [comment]
I am also facing this issue

* What went wrong:
Execution failed for task ':react-native-keychain:extractReleaseAnnotations'.
> Lint infrastructure error
  Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.android.tools.lint.gradle.api.ReflectiveLintRunner.extractAnnotations(ReflectiveLintRunner.kt:63)
        at com.android.build.gradle.tasks.ExtractAnnotations.doTaskAction(ExtractAnnotations.java:227)
        at com.android.build.gradle.internal.tasks.NonIncrementalTask$taskAction$$inlined$recordTaskAction$1.invoke(BaseTask.kt:63)
        at com.android.build.gradle.internal.tasks.Blocks.recordSpan(Blocks.java:51)
        at com.android.build.gradle.internal.tasks.NonIncrementalTask.taskAction(NonIncrementalTask.kt:90)
        at jdk.internal.reflect.GeneratedMethodAccessor890.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:104)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:58)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:51)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:29)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$2.run(ExecuteActionsTaskExecuter.java:494)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:56)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$run$1(DefaultBuildOperationExecutor.java:71)
        at org.gradle.internal.operations.UnmanagedBuildOperationWrapper.runWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:45)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:71)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:479)

**Comment by maciejsiiminski** [comment]
So I battled with this error today for a whole day and I managed to get rid of it by uninstalling and reinstalling JDK. I don't know if it would work for anyone else but it worked for me.
