### ISSUE TITLE
[ ANDROID - RELEASE BUILD ] - App Crashes - RNKeychain ^8.1.0 - RN 0.67.0

### ISSUE THREAD

**Issue by PRA1995SAG** [oblador/react-native-keychain#559]
Hello community, thanks for making such useful library

> The debug build runs on simulator & real device, though release build crashes ( Android )
### react-native-info
```
System:
    OS: macOS 12.4
    CPU: (8) arm64 Apple M1
    Memory: 114.66 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.5.0 - /opt/homebrew/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.12.1 - /opt/homebrew/bin/npm
    Watchman: 2022.06.06.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
    Android SDK:
      API Levels: 23, 28, 29, 30, 31
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0
      System Images: android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Intel x86 Atom_64, android-30 | Google APIs ARM 64 v8a, android-31 | Google Play ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8512546
    Xcode: 13.0/13A233 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.67.0 => 0.67.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```
### react-native-keychain
```
    "react-native-keychain": "^8.1.0",
```

### logcat
```
2022-07-22 20:28:49.198 11171-11202/com.xyz V/RNKeychainManager: warming up started at 24258946587691
2022-07-22 20:28:49.217 11171-11202/com.xyz D/RNKeychainManager: Probe cipher storage: g
2022-07-22 20:28:49.217 11171-11202/com.xyz D/RNKeychainManager: Probe cipher storage: h
2022-07-22 20:28:49.217 11171-11202/com.xyz D/RNKeychainManager: Probe cipher storage: i
2022-07-22 20:28:49.217 11171-11202/com.xyz D/RNKeychainManager: Selected storage: h
2022-07-22 20:28:49.233 11171-11196/com.xyz D/SoLoader: Loaded: libreactnativejni.so
2022-07-22 20:28:49.256 398-398/? I/keystore: del USRPKEY_AndroidKeyStore#supportsSecureHardware 10171
2022-07-22 20:28:49.258 398-398/? I/keystore: del USRSKEY_AndroidKeyStore#supportsSecureHardware 10171
2022-07-22 20:28:49.258 398-398/? I/keystore: del USRCERT_AndroidKeyStore#supportsSecureHardware 10171
2022-07-22 20:28:49.258 398-398/? I/keystore: del CACERT_AndroidKeyStore#supportsSecureHardware 10171
2022-07-22 20:28:49.309 398-398/? I/keystore: del USRPKEY_AndroidKeyStore#supportsSecureHardware 10171
2022-07-22 20:28:49.311 398-398/? I/keystore: del USRCERT_AndroidKeyStore#supportsSecureHardware 10171
2022-07-22 20:28:49.311 398-398/? I/keystore: del CACERT_AndroidKeyStore#supportsSecureHardware 10171
2022-07-22 20:28:49.311 398-398/? I/keystore: del USRPKEY_warmingUp 10171
2022-07-22 20:28:49.311 398-398/? I/keystore: del USRCERT_warmingUp 10171
2022-07-22 20:28:49.312 398-398/? I/keystore: del CACERT_warmingUp 10171
2022-07-22 20:28:49.312 11171-11202/com.xyz E/KeyStore: generateKeyInternal failed on request -68
2022-07-22 20:28:49.312 398-398/? I/keystore: del USRPKEY_warmingUp 10171
2022-07-22 20:28:49.312 398-398/? I/keystore: del USRSKEY_warmingUp 10171
2022-07-22 20:28:49.312 398-398/? I/keystore: del USRCERT_warmingUp 10171
2022-07-22 20:28:49.312 398-398/? I/keystore: del CACERT_warmingUp 10171
2022-07-22 20:28:49.317 11171-11202/com.xyz W/b: StrongBox security storage is not available.
    android.security.keystore.StrongBoxUnavailableException: Failed to generate key
        at android.security.keystore.AndroidKeyStoreKeyGeneratorSpi.engineGenerateKey(AndroidKeyStoreKeyGeneratorSpi.java:328)
        at javax.crypto.KeyGenerator.generateKey(KeyGenerator.java:612)
        at i6.h.r(Unknown Source:13)
        at i6.b.F(Unknown Source:19)
        at i6.b.E(Unknown Source:1)
        at i6.b.s(Unknown Source:26)
        at com.oblador.keychain.KeychainModule.internalWarmingBestCipher(Unknown Source:48)
        at com.oblador.keychain.KeychainModule.a(Unknown Source:0)
        at com.oblador.keychain.b.run(Unknown Source:2)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: android.security.KeyStoreException: No StrongBox available
        at android.security.keystore.AndroidKeyStoreKeyGeneratorSpi.engineGenerateKey(AndroidKeyStoreKeyGeneratorSpi.java:328) 
        at javax.crypto.KeyGenerator.generateKey(KeyGenerator.java:612) 
        at i6.h.r(Unknown Source:13) 
        at i6.b.F(Unknown Source:19) 
        at i6.b.E(Unknown Source:1) 
        at i6.b.s(Unknown Source:26) 
        at com.oblador.keychain.KeychainModule.internalWarmingBestCipher(Unknown Source:48) 
        at com.oblador.keychain.KeychainModule.a(Unknown Source:0) 
        at com.oblador.keychain.b.run(Unknown Source:2) 
        at java.lang.Thread.run(Thread.java:923) 
2022-07-22 20:28:49.317 398-398/? I/keystore: del USRPKEY_warmingUp 10171
2022-07-22 20:28:49.317 398-398/? I/keystore: del USRSKEY_warmingUp 10171
2022-07-22 20:28:49.317 398-398/? I/keystore: del USRCERT_warmingUp 10171
2022-07-22 20:28:49.317 398-398/? I/keystore: del CACERT_warmingUp 10171
2022-07-22 20:28:49.326 11171-11202/com.xyz V/RNKeychainManager: warming up takes: 128 ms
```
_( pasted rnkeychain related logs only)_

### what I've tried ?
https://github.com/oblador/react-native-keychain/issues/314#issuecomment-668563510

**Comment by PRA1995SAG** [comment]
Idk, what wrong I'm doing ... ?

The logcat shows same results for 7.0.0
```
"react-native-keychain": "7.0.0"
```
> Utility/keychain.js
```js
import * as Keychain from 'react-native-keychain';
import Config from 'react-native-config';

const storeConfig = {
  accessible: Keychain.ACCESSIBLE.AFTER_FIRST_UNLOCK_THIS_DEVICE_ONLY,
};

export async function storeUserDataToKeystore(username, password) {
  try {
    const response = await Keychain.setInternetCredentials(
      Config.USER_DATA,
      username,
      password,
      storeConfig
    );
    return response;
  } catch (error) {
    throw new Error('Could not store user data, please try again');
  }
}

export async function storeFCMToKeystore(username, password) {
  try {
    await Keychain.setInternetCredentials(Config.FCM_TOKEN, username, password, storeConfig);
  } catch (error) {
    throw new Error('Could not store token, please try again');
  }
}

export async function storeUserProfileToKeystore(username, password) {
  try {
    await Keychain.setInternetCredentials(Config.PROFILE_PIC, username, password, storeConfig);
  } catch (error) {
    throw new Error('Could not store token, please try again');
  }
}

export async function resetUserDataFromKeystore() {
  try {
    await Keychain.resetInternetCredentials(Config.USER_DATA);
  } catch (error) {
    throw new Error('could not reset data');
  }
}

export async function retrieveUserDataFromKeystore() {
  try {
    const { server, username, password } = await Keychain.getInternetCredentials(
      Config.USER_DATA,
      storeConfig
    );
    return password ? JSON.parse(password) : '';
  } catch (error) {
    throw new Error('Could not retrieve user data, please try again');
  }
}

export async function retrieveFCMFromKeystore() {
  try {
    const response = await Keychain.getInternetCredentials(Config.FCM_TOKEN, storeConfig);
    return response;
  } catch (error) {
    throw new Error('Could not retrieve token, please try again');
  }
}

export async function retrieveUserProfileFromKeystore() {
  try {
    const response = await Keychain.getInternetCredentials(Config.PROFILE_PIC, storeConfig);
    return response;
  } catch (error) {
    throw new Error('Could not store token, please try again');
  }
}

```

**Comment by jakubgrzelak** [comment]
the same issue :(

**Comment by PRA1995SAG** [comment]
@jakubgrzelak , For my case, I resolved the issue by building the RELEASE APK correct way!
(I think this **not an issue from `RNKeychain` side** at all ! )

I was building the `release APK` like below:

```bash
cd android
./gradlew bundleRelease
```
Indeed, it bundles the Javaccirpt code, though it was not enough

after configuring gradle things (like [mentioned here](https://reactnative.dev/docs/0.67/signed-apk-android))

you've two options
1.    (ref. stackoverflow answers) [reference here](https://stackoverflow.com/questions/35935060/how-can-i-generate-an-apk-that-can-run-without-server-with-react-native)
```bash
 react-native bundle --platform android --dev false --entry-file index.android.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res/
```

2.    react native docs has given below command [reference here](https://reactnative.dev/docs/0.67/integration-with-existing-apps#creating-a-release-build-in-android-studio):
```bash
npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/com/your-company-name/app-package-name/src/main/assets/index.android.bundle --assets-dest android/com/your-company-name/app-package-name/src/main/res/
```

(first one worked for me)

> Moral: 1. create JS bundle then 2. generate .AAB / .APK
> Same applies for ios too, we need to create `main.jsbundle` first then we can proceed with build

_If this does not help, feel free to share your approach/code, closing this issue for now !_
