### ISSUE TITLE
Keychain.getGenericPassword randomly returns false

### ISSUE THREAD

**Issue by dnvarun** [oblador/react-native-keychain#594]
I am not able to reproduce this in development but some of our users in production are randomly facing this error and suddenly get logged out. Are there any workarounds for this?

FYI We are using {service} attribute for setting and getting the token

**Comment by KonstantinZhukovskij** [comment]
We have the same problem and this is only reproducible on android. Can't reproduce step by step

**Comment by Hady207** [comment]
Any update on this ?
Im also facing the same issue.

**Comment by roxlu** [comment]
Same here, at least when testing in the Android emulator. It seems that the service isn't available during the [2nd re-render](https://react.dev/reference/react/StrictMode) that React does during development and strict mode.  This issue is triggered when I run code like shown below. The `onLoadOk()` will be called twice, once with the stored data and with `false` for the second time. 

```js
  const load = async() => {

    const onLoadOk = (stored) => {
      console.log('LoadOk: ', stored);
    };

    const onLoadError = (err) => {
      console.log('LoadError: ', err);
    };
    
    Keychain
      .getGenericPassword({service: 'api'})
      .then(onLoadOk)
      .catch(onLoadError);
    
  };

  useEffect(() => {
    load();
  }, []);

```

When using the following code I noticed that my service wasn't there during the 2nd execution:

```js
  const load = async() => {

    const onLoadOk = (stored) => {
      console.log('LoadOk: ', stored);
    };

    const onLoadError = (err) => {
      console.log('LoadError: ', err);
    };

    await Keychain.getAllGenericPasswordServices()
      .then(onLoadOk)
      .catch(onLoadError);
  };

  useEffect(() => {
    load();
  }, []);

```

The above snippet logs:
```
LoadOk:  ["api"]
LoadOk:  []
```
When inspecting logcat I noticed:

```log
StrongBox security storage is not available.
java.security.ProviderException: Failed to generate key pair.
at android.security.keystore2.AndroidKeyStoreKeyPairGeneratorSpi.generateKeyPairHelper(AndroidKeyStoreKeyPairGeneratorSpi.java:717)
at android.security.keystore2.AndroidKeyStoreKeyPairGeneratorSpi.generateKeyPair(AndroidKeyStoreKeyPairGeneratorSpi.java:627)
at java.security.KeyPairGenerator$Delegate.generateKeyPair(KeyPairGenerator.java:746)
at com.oblador.keychain.cipherStorage.CipherStorageKeystoreRsaEcb.generateKey(CipherStorageKeystoreRsaEcb.java:269)
at com.oblador.keychain.cipherStorage.CipherStorageBase.tryGenerateStrongBoxSecurityKey(CipherStorageBase.java:475)
at com.oblador.keychain.cipherStorage.CipherStorageBase.tryGenerateStrongBoxSecurityKey(CipherStorageBase.java:460)
at com.oblador.keychain.cipherStorage.CipherStorageBase.generateKeyAndStoreUnderAlias(CipherStorageBase.java:413)
at com.oblador.keychain.KeychainModule.internalWarmingBestCipher(KeychainModule.java:174)
at com.oblador.keychain.KeychainModule.$r8$lambda$01EbvFUsGjOVmyfYmQa0MQI7auI(Unknown Source:0)
at com.oblador.keychain.KeychainModule$$ExternalSyntheticLambda0.run(Unknown Source:2)
at java.lang.Thread.run(Thread.java:1012)
Caused by: android.security.KeyStoreException: Unsupported key size (internal Keystore code: -6 message: In generate_key.
                                                                      
                                                                      Caused by:
                                                                      0: While generating Key without explicit attestation key.
                                                                      1: Error::Km(ErrorCode(-6))) (public error code: 12 internal Keystore code: -6)
at android.security.KeyStore2.getKeyStoreException(KeyStore2.java:369)
at android.security.KeyStoreSecurityLevel.handleExceptions(KeyStoreSecurityLevel.java:57)
at android.security.KeyStoreSecurityLevel.generateKey(KeyStoreSecurityLevel.java:145)
at android.security.keystore2.AndroidKeyStoreKeyPairGeneratorSpi.generateKeyPairHelper(AndroidKeyStoreKeyPairGeneratorSpi.java:690)
... 10 more
```

Some specs that might be useful:

```
System:
  OS: Linux 6.7 Arch Linux
  CPU: (24) x64 Intel(R) Core(TM) i9-10920X CPU @ 3.50GHz
  Memory: 41.24 GB / 62.49 GB
  Shell:
    version: 5.2.26
    path: /bin/bash
Binaries:
  Node:
    version: 18.12.1
    path: ~/.nvm/versions/node/v18.12.1/bin/node
  Yarn:
    version: 1.22.19
    path: ~/.nvm/versions/node/v18.12.1/bin/yarn
  npm:
    version: 8.19.2
    path: ~/.nvm/versions/node/v18.12.1/bin/npm
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
IDEs:
  Android Studio: AI-231.9392.1.2311.11330709
Languages:
  Java:
    version: 17.0.10
    path: /usr/bin/javac
  Ruby:
    version: 3.0.6
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.3
    wanted: 0.73.3
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: false
```

And package.json:
```
  "dependencies": {
    "@react-navigation/native": "^6.1.9",
    "@react-navigation/native-stack": "^6.9.17",
    "react": "18.2.0",
    "react-intl": "^6.6.2",
    "react-native": "0.73.3",
    "react-native-get-random-values": "^1.10.0",
    "react-native-keychain": "^8.1.2",
    "react-native-safe-area-context": "^4.9.0",
    "react-native-screens": "^3.29.0",
    "react-native-sqlite-storage": "^6.0.1",
    "react-native-vision-camera": "^3.8.2",
    "uuid": "^9.0.1",
    "zod": "^3.22.4"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@babel/preset-env": "^7.20.0",
    "@babel/runtime": "^7.20.0",
    "@react-native/babel-preset": "0.73.20",
    "@react-native/eslint-config": "0.73.2",
    "@react-native/metro-config": "0.73.4",
    "@react-native/typescript-config": "0.73.1",
    "@types/react": "^18.2.6",
    "@types/react-test-renderer": "^18.0.0",
    "babel-jest": "^29.6.3",
    "babel-plugin-module-resolver": "^5.0.0",
    "eslint": "^8.19.0",
    "jest": "^29.6.3",
    "prettier": "2.8.8",
    "react-test-renderer": "18.2.0",
    "typescript": "5.0.4"
  },

```

**Comment by abdulragib** [comment]
i got same issue

**Comment by Brma1048** [comment]
I have the same issue, when I safe the password to the keychain and close the app directly after that and want to get the password I receive false, but only for the first time. When I close the app again and open again it works. 
Version: 9.0.0
RN: 0.75.4
OS: Android 14, Pixel 7
