### ISSUE TITLE
android linux crash

### ISSUE THREAD

**Issue by dingsq820** [oblador/react-native-keychain#615]
**adb logcat:**
10-12 10:55:55.214   255   255 E keystore2: keystore2::error: In get_security_level: No such security level.
10-12 10:55:55.214   255   255 E keystore2: 
10-12 10:55:55.214   255   255 E keystore2: Caused by:
10-12 10:55:55.214   255   255 E keystore2:     Error::Km(ErrorCode(-68))
10-12 10:55:55.223  4341  4495 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.frescosupport.FrescoBasedReactTextInlineImageViewManager
10-12 10:55:55.225  4341  4495 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.frescosupport.FrescoBasedReactTextInlineImageShadowNode
10-12 10:55:55.228  4341  4495 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.image.ReactImageManager
10-12 10:55:55.234  4341  4495 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.modal.ReactModalHostManager
10-12 10:55:55.237  4341  4495 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.modal.ModalHostShadowNode
10-12 10:55:55.239  4341  4495 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactRawTextManager
10-12 10:55:55.242  4341  4495 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactRawTextShadowNode
10-12 10:55:55.244  4341  4495 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.textinput.ReactTextInputManager
10-12 10:55:55.246  4341  4495 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.textinput.ReactTextInputShadowNode
10-12 10:55:55.248  4341  4495 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactTextViewManager
10-12 10:55:55.249  4341  4495 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactTextShadowNode
10-12 10:55:55.250  4341  4495 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.view.ReactViewManager
10-12 10:55:55.251  4341  4495 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactVirtualTextViewManager
10-12 10:55:55.252  4341  4495 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactVirtualTextShadowNode
10-12 10:55:55.259  4341  4495 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.unimplementedview.ReactUnimplementedViewManager
10-12 10:55:55.262  4341  4495 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.swmansion.gesturehandler.react.RNGestureHandlerRootViewManager
10-12 10:55:55.263  4341  4495 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.swmansion.gesturehandler.react.RNGestureHandlerButtonViewManager
10-12 10:55:55.266  4341  4495 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.brentvatne.exoplayer.ReactExoplayerViewManager
10-12 10:55:55.268  4341  4492 W CipherStorageBase: StrongBox security storage is not available.
10-12 10:55:55.268  4341  4492 W CipherStorageBase: android.security.keystore.StrongBoxUnavailableException: Failed to generate key
10-12 10:55:55.268  4341  4492 W CipherStorageBase:     at android.security.keystore2.AndroidKeyStoreKeyGeneratorSpi.engineGenerateKey(AndroidKeyStoreKeyGeneratorSpi.java:411)
10-12 10:55:55.268  4341  4492 W CipherStorageBase:     at javax.crypto.KeyGenerator.generateKey(KeyGenerator.java:612)
10-12 10:55:55.268  4341  4492 W CipherStorageBase:     at com.oblador.keychain.cipherStorage.CipherStorageKeystoreAesCbc.generateKey(CipherStorageKeystoreAesCbc.java:228)
10-12 10:55:55.268  4341  4492 W CipherStorageBase:     at com.oblador.keychain.cipherStorage.CipherStorageBase.tryGenerateStrongBoxSecurityKey(CipherStorageBase.java:475)
10-12 10:55:55.268  4341  4492 W CipherStorageBase:     at com.oblador.keychain.cipherStorage.CipherStorageBase.tryGenerateStrongBoxSecurityKey(CipherStorageBase.java:460)
10-12 10:55:55.268  4341  4492 W CipherStorageBase:     at com.oblador.keychain.cipherStorage.CipherStorageBase.generateKeyAndStoreUnderAlias(CipherStorageBase.java:413)
10-12 10:55:55.268  4341  4492 W CipherStorageBase:     at com.oblador.keychain.KeychainModule.internalWarmingBestCipher(KeychainModule.java:174)
10-12 10:55:55.268  4341  4492 W CipherStorageBase:     at com.oblador.keychain.KeychainModule.$r8$lambda$DYujhqpjRgfFQ_gyuwMwyxxqDlk(Unknown Source:0)
10-12 10:55:55.268  4341  4492 W CipherStorageBase:     at com.oblador.keychain.KeychainModule$$ExternalSyntheticLambda0.run(Unknown Source:2)
10-12 10:55:55.268  4341  4492 W CipherStorageBase:     at java.lang.Thread.run(Thread.java:1012)
10-12 10:55:55.268  4341  4492 W CipherStorageBase: Caused by: android.security.KeyStoreException: No StrongBox available (public error code: 12 internal Keystore code: -68)
10-12 10:55:55.268  4341  4492 W CipherStorageBase:     ... 10 more

**system info:**
System:
    OS: Linux 6.2 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (8) x64 Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz
    Memory: 7.61 GB / 15.40 GB
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 20.1.0 - /tmp/yarn--1697093282881-0.1734834581479181/node
    Yarn: 1.22.19 - /tmp/yarn--1697093282881-0.1734834581479181/yarn
    npm: 9.6.4 - ~/.nvm/versions/node/v20.1.0/bin/npm
    Watchman: 2022.07.04.00 - /home/linuxbrew/.linuxbrew/bin/watchman
  SDKs:
    Android SDK:
      API Levels: 23, 25, 26, 28, 30, 31, 33
      Build Tools: 28.0.3, 30.0.2, 30.0.3, 31.0.0, 33.0.0
      System Images: android-31 | Intel x86 Atom_64, android-31 | Google APIs Intel x86 Atom_64, android-31 | Google Play Intel x86 Atom_64, android-33 | Google APIs Intel x86_64 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 11.0.20.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.12 => 0.71.12 
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by rorycaseyap** [comment]
@dingsq820 did you manage to resolve this? Having the same issue.

**Comment by tnghia944** [comment]
hi @rorycaseyap , @dingsq820 
I have the same error, have you fixed it?

**Comment by DorianMazur** [comment]
Hi @dingsq820,
Could you please provide more context and the steps to reproduce this issue?
