### ISSUE TITLE
Encrypt and decrypt failing on latest Samsung OS

### ISSUE THREAD

**Issue by joarkosberg** [oblador/react-native-keychain#617]
This might not be related to this library, but I am opening a issue to discuss, in case it is or others are facing the same problem. 

**Description**

From the latest OS update on Samsung phones (October 2023), a lot of devices has started failing encrypting and decrypting with the library. It is only Samsung phones on the newest OS, and it fails every time. 

**Versions**

RN: 0.72.5
React-native-keychain: 8.1.2

**Error** 

`Could not decrypt data with alias:`
and
`Could not encrypt data with alias:`

**Comment by lucasftcruz** [comment]
Related issues:
- https://github.com/oblador/react-native-keychain/issues/458
- https://github.com/oblador/react-native-keychain/issues/567

**Comment by joarkosberg** [comment]
@lucasftcruz Thanks!

**Comment by alexandrius** [comment]
@lucasftcruz Just want to note that those 2 issues are different from newer Samsung issues

**Comment by Turtus** [comment]
traced to 
cipher.init(Cipher.DECRYPT_MODE, key, iv);
java.security.InvalidKeyException: Keystore operation failed 
seems all stored data in Samsung is broken now

**Comment by Emielvdongen** [comment]
I am not sure if I encounter the same problem, but here it is. I have an mobile application where users can log in.

RN: 0.71.0
React-native-keychain: 8.1.1

I get the following error message:
Error: Decrypt failed.

It was working previously and still is on my iPhone XR (also in all kinds of simulators), but not in the iPhone 15 Pro Max (real device). 

Setting the app version back, does not work (which would suggest it is a problem of the phone right?).

Any thoughts?

**Comment by androideveloper** [comment]
Full stacktrace is this:

```
com.oblador.keychain.exceptions.CryptoFailedException: Could not encrypt data with alias: 
	at com.oblador.keychain.cipherStorage.CipherStorageKeystoreAesCbc.encrypt(CipherStorageKeystoreAesCbc.java:122)
	at com.oblador.keychain.KeychainModule.setGenericPassword(KeychainModule.java:224)
	at com.oblador.keychain.KeychainModule.setGenericPasswordForOptions(KeychainModule.java:253)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
	at com.facebook.jni.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.security.InvalidKeyException: Keystore operation failed
	at android.security.keystore2.KeyStoreCryptoOperationUtils.getInvalidKeyException(KeyStoreCryptoOperationUtils.java:130)
	at android.security.keystore2.KeyStoreCryptoOperationUtils.getExceptionForCipherInit(KeyStoreCryptoOperationUtils.java:154)
	at android.security.keystore2.AndroidKeyStoreCipherSpiBase.ensureKeystoreOperationInitialized(AndroidKeyStoreCipherSpiBase.java:345)
	at android.security.keystore2.AndroidKeyStoreCipherSpiBase.engineInit(AndroidKeyStoreCipherSpiBase.java:177)
	at javax.crypto.Cipher.tryTransformWithProvider(Cipher.java:2985)
	at javax.crypto.Cipher.tryCombinations(Cipher.java:2892)
	at javax.crypto.Cipher$SpiAndProviderUpdater.updateAndGetSpiAndProvider(Cipher.java:2797)
	at javax.crypto.Cipher.chooseProvider(Cipher.java:774)
	at javax.crypto.Cipher.init(Cipher.java:1144)
	at javax.crypto.Cipher.init(Cipher.java:1085)
	at com.oblador.keychain.cipherStorage.CipherStorageBase$IV.lambda$static$0(CipherStorageBase.java:544)
	at com.oblador.keychain.cipherStorage.CipherStorageBase$IV$$ExternalSyntheticLambda0.initialize(Unknown Source:0)
	at com.oblador.keychain.cipherStorage.CipherStorageBase.encryptString(CipherStorageBase.java:353)
	at com.oblador.keychain.cipherStorage.CipherStorageKeystoreAesCbc.encryptString(CipherStorageKeystoreAesCbc.java:263)
	at com.oblador.keychain.cipherStorage.CipherStorageKeystoreAesCbc.encrypt(CipherStorageKeystoreAesCbc.java:118)
	... 13 more
Caused by: android.security.KeyStoreException: Invalid key blob (internal Keystore code: -33 message: In create_operation: Failed to begin operation. 10032

Caused by:
    0: In KeystoreSecurityLevel::upgrade_keyblob_if_required_with.
    1: In utils::upgrade_keyblob_if_required_with: Calling km_op.
    2: Error::Km(ErrorCode(-33))) (public error code: 10 internal Keystore code: -33)
	at android.security.KeyStore2.getKeyStoreException(KeyStore2.java:418)
	at android.security.KeyStoreSecurityLevel.createOperation(KeyStoreSecurityLevel.java:123)
	at android.security.keystore2.AndroidKeyStoreCipherSpiBase.ensureKeystoreOperationInitialized(AndroidKeyStoreCipherSpiBase.java:340)
	... 25 more
```

**Comment by ViktorOsadchyi** [comment]
Hi, any updates ?

In our application, this issue also began to arise frequently. At Sentry, we see that most often this problem occurs among Samsung users, but there are also cases with Honor, Huawei and ZTE. The most common version of Android is 13, and 10 is also present.

Versions

RN: 0.72.5
react-native-keychain: 8.1.1

Error

<img width="251" alt="Screenshot 2023-11-16 at 18 36 03" src="https://github.com/oblador/react-native-keychain/assets/24491018/4d29a56d-9a9a-4da6-a212-a3f50de89fc3">

**Comment by joarkosberg** [comment]
For me the error went died down after the update from Samsung. So seems to be fixed at their side.

@ViktorOsadchyi Have you seen a increase in the error, or is it going down?

**Comment by ViktorOsadchyi** [comment]
@joarkosberg the number of users with this issue is not increasing. But new events are appearing. I'll probably have to wait until they update the version.

**Comment by androideveloper** [comment]
New patch from Samsung automatically fixed it for us.

**Comment by yberstad** [comment]
Has this started again for Samsung Galaxy S24 Ultra devices for other than us?

![image](https://github.com/oblador/react-native-keychain/assets/2823722/91302a6b-eca9-44b4-b916-4f1ca371915e)

Suspect that this is the reason:
https://www.sammobile.com/news/galaxy-s24-june-2024-security-update-europe

**Comment by kevinranks** [comment]
Just got this on my S24 as well, shortly after installing the June security update. Tested on my S21 after installing the June security update and was not able to reproduce it.

**Comment by ddytert** [comment]
Hi @yberstad, we see the same issue in Bugsnag, mostly on Samsung Galaxy S24 Ultra devices. Do you have any updates on this issue? Do you know if Samsung is aware of this bug?
![image](https://github.com/user-attachments/assets/5caf64eb-d840-4328-964d-54c055773633)

**Comment by ohabbers** [comment]
Hi @ddytert, Unfortunately I am not aware of any fix for this issue. It seems very similar to other issues we have had after Samsung has released new security patches. The only solution we have so far is to ask the customer to reinstall the app.

**Comment by yberstad** [comment]
Hi again! 
Once more we are experiencing issues with Samsung devices. 
Are others experience this?

I suspect that this is due to this?
https://www.sammyfans.com/2024/10/30/samsung-starts-november-2024-security-update-rollout/

![CleanShot 2024-11-03 at 21 17 14](https://github.com/user-attachments/assets/c1e4a124-8720-4149-8c7b-a3a44974da4d)

**Comment by steavenb** [comment]
The latest version never works for me, but I had no issues with an older version of this package on another project. The working version for me is 8.1.2

**Comment by yberstad** [comment]
I just received feedback from a customer stating that the latest update from Samsung has made our app work again. I suspect this might be related to the November update: https://doc.samsungmobile.com/SM-G988B/DBT/doc.html

**Comment by GonzaloAszyn** [comment]
Hi, I'm using react-native-keychain@8.2.0 and all my users that have a Samsung S25, Keychain Storage is not working correctly for them. Asked them for a screenshot and they have the latest software update and security patch installed.
