### ISSUE TITLE
Android crash from adding react-native-keychain package

### ISSUE THREAD

**Issue by Hyllesen** [oblador/react-native-keychain#623]
I get this error from logcat on Android startup after using `yarn add react-native-keychain `

Tested with no implementation/using of the package in the React Native JavaScript code.

```FATAL EXCEPTION: main
Process: com.datingapp, PID: 17317
java.lang.RuntimeException: Unable to get provider androidx.startup.InitializationProvider: android.content.res.Resources$NotFoundException: String resource ID #0x7f0f001c
	at android.app.ActivityThread.installProvider(ActivityThread.java:7467)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6973)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6744)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2133)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7872)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: android.content.res.Resources$NotFoundException: String resource ID #0x7f0f001c
	at android.content.res.Resources.getText(Resources.java:453)
	at android.content.res.Resources.getString(Resources.java:546)
	at android.content.Context.getString(Context.java:762)
	at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:216)
	at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:206)
	at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:45)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2451)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2421)
	at android.app.ActivityThread.installProvider(ActivityThread.java:7462)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6973) 
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6744) 
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0) 
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2133) 
	at android.os.Handler.dispatchMessage(Handler.java:106) 
	at android.os.Looper.loopOnce(Looper.java:201) 
	at android.os.Looper.loop(Looper.java:288) 
	at android.app.ActivityThread.main(ActivityThread.java:7872) 
	at java.lang.reflect.Method.invoke(Native Method) 
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936) 
 
```

"react-native": "0.73.4",
    "react-native-keychain": "^8.1.3",

**Comment by Hyllesen** [comment]
Turns out doing a `gradlew clean` solved the issue
