### ISSUE TITLE
Issue when running Jest tests

### ISSUE THREAD

**Issue by mounibec** [oblador/react-native-keychain#72]
When I run this code

```
import * as KeychainHandler from 'react-native-keychain';
function save(username, password) {
  return KeychainHandler.setGenericPassword(username, username).then(() => true);
}
it('KeyChain are saved correctly', () => {
  jest.useFakeTimers();
  expect.assertions(1);
  save('me', 'mypassword').then(data => expect(result).toEqual(true));
});
```

I get this error:

```
> jest

 FAIL  __tests__/index.js
  ● KeyChain are saved correctly

    TypeError: Cannot read property 'setGenericPasswordForOptions' of undefined

      at Object.setGenericPassword (node_modules/react-native-keychain/index.js:125:906)
      at save (__tests__/index.js:19:24)
      at Object.<anonymous> (__tests__/index.js:25:1)
      at tryCallTwo (node_modules/promise/lib/core.js:45:5)
      at doResolve (node_modules/promise/lib/core.js:200:13)
      at new Promise (node_modules/promise/lib/core.js:66:3)
      at Promise.resolve.then.el (node_modules/p-map/index.js:42:16)

  ● KeyChain are saved correctly

    expect.assertions(1)

    Expected one assertion to be called but only received zero assertion calls.

      at addAssertionErrors (node_modules/jest-jasmine2/build/setup-jest-globals.js:68:21)
      at tryCallOne (node_modules/promise/lib/core.js:37:12)
      at node_modules/promise/lib/core.js:123:15
      at flush (node_modules/asap/raw.js:50:29)
      at _combinedTickCallback (internal/process/next_tick.js:67:7)
      at process._tickCallback (internal/process/next_tick.js:98:9)

  ✕ KeyChain are saved correctly (2ms)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        0.41s, estimated 1s
Ran all test suites.
npm ERR! Test failed.  See above for more details.
```

my config is:

```
"devDependencies": {
    "babel-jest": "20.0.1",
    "babel-plugin-transform-flow-strip-types": "6.22.0",
    "babel-preset-react-native": "1.9.2",
    "jest": "20.0.1",
    "react-test-renderer": "16.0.0-alpha.6"
  },
  "jest": {
    "automock": false,
    "preset": "react-native",
    "testEnvironment": "node"
  }
```

I'm a missing something ?

**Comment by vonovak** [comment]
did you mock `react-native-keychain`?

**Comment by mounibec** [comment]
Yes and it works. Sorry I didn't get back to you!

I did something like this:

```
jest.mock('react-native-keychain', () => {
  return {
    setGenericPassword: jest.fn((username, password) => { {...}),
    getGenericPassword: jest.fn(() => {...}),
    resetGenericPassword: jest.fn(() =>  {...}),
  }
});
```

**Comment by ray0925** [comment]
Hi, @mounibec 
may I know what's the meaning of three dots in your mock?

**Comment by OmarBasem** [comment]
Mocking react-native-keychain has to return a promise.

`jest.mock('react-native-keychain', () => ({
    setGenericPassword: jest.fn(() => Promise.resolve('mockPass')),
    getGenericPassword: jest.fn(() => Promise.resolve('mockPass')),
    resetGenericPassword: jest.fn(() => Promise.resolve(null)),
}));`
